### ISSUE TITLE
Beta 1.1.3

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_config_keys#10]
![default](https://user-images.githubusercontent.com/7419630/36372490-47b28b32-1576-11e8-8411-144bec422bc1.png)

1. Переименовал и переместил кнопки для отчетов

2. Добавил кнопку `Open code`, чтобы открывать реализацию команды плагина.
Но это будет видно не всем, а только тем, кто в user.json добавит
`"config_keys_with_open":true`

**Comment by Alexey-T** [comment]
Спасибо, но лучше «Report to new tan”

**Comment by Alexey-T** [comment]
Report to new tab.

**Comment by kvichans** [comment]
Ок "to new Tab"

Потестируйте open -  там есть где ошибиться

**Comment by Alexey-T** [comment]
У меня плагин не стоит , неудобно тестить
