### ISSUE TITLE
cannot find key.json

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_keys#4]
на новой инсталяции Куд.

```
cd_config_keys.py line 218 [..]
keys = apx._json_loads(open(keys_json).read())
FileNotFoundError: [Errno 2] No such file..
```

**Comment by kvichans** [comment]
Что означает "на новой"? что изменилось?

**Comment by kvichans** [comment]
А-а-а!
Еще ни одного сочетания не назначено.
ToDo

**Comment by kvichans** [comment]
У-у-у, беда. В какой момент штатные сочетания перетекают из ядра в keys.json?

**Comment by Alexey-T** [comment]
При закр. длг по ок

**Comment by kvichans** [comment]
Отбой паники - нет беды. Нормально работает плагин.
