### ISSUE TITLE
title string

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_keys#7]
Use one string. now is 1)configure  hotkeys 2) configure keymap 3)module cuda_config_keys

**Comment by kvichans** [comment]
Согласен, что 1) и 2) нужно привести к единому термину
А что с 3)? Это никому не мешает

Переведу 1)+2) на `Hotkeys`

**Comment by Alexey-T** [comment]
Еще на вс.сл. file-name (zip)

**Comment by kvichans** [comment]
?
