### ISSUE TITLE
Wish for dialog

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_config_keys#9]
1)
```
Filter by command: [..........]
Filter by hotkey: [.........]
Combine filters by: (*) and  ( ) or
```
These 3 lines instead of current 2 lines
```
In command              ......
[...]                            ........
```

2)
Button captions:
- Report to HTML
- Report to new tab
Make button width bigger

**Comment by Alexey-T** [comment]
3) Width of column 0 too big (even on Linix big font)

**Comment by kvichans** [comment]
1. Нет. Так, как вы предлагаете, плохо расширяется на новые условия
Визуальная логика диалога
![default](https://user-images.githubusercontent.com/7419630/36265784-05fbee74-1281-11e8-998d-7f7f056fe264.png)
опирается на колонки
- Фильтр по имени + имена
- Фильтр по хоткею + хоткеи + Добавить/Удалить
- [Фильтр по снипу + снипы + Добавить/Удалить]

2. Хорошо. Добавлю "Report" в имена кнопок и перемещу их под первую колонку

3. Бывают очень длинные имена у команд.
Могу сделать **у**же колонки с хоткеями. Делать?

**Comment by Alexey-T** [comment]
3.  не понял про "колонки с хоткеями", это что.
